version: '3'

services:

  # Postgres
  bibliotheque-postgres:
    image: "postgres:13.2-alpine"
    container_name: bibliotheque-postgres

    volumes:
      - bibliotheque-data:/var/lib/postgresql/data

    ports:
      - 5433:5432

    environment:
      - POSTGRES_DB=bibliotheque
      - POSTGRES_USER=groupe2ws
      - POSTGRES_PASSWORD=12345

  # Back-end Spring boot application
  bibliotheque-app:
    build:
      context: ./
      args:
        maven_build_env: mvn -f pom.xml clean package

    container_name: bibliotheque-app-local

    ports:
      - 8080:8080
    links:
      - bibliotheque-postgres

volumes:
  bibliotheque-data:
