---

# BUILD PREPROD APP IMAGE FROM NEXUS AND PUSH DOCKERHUB
- name: Build preprod app image from nexus and send it to DockerHub
  docker_image:
    build:
      path: "{{ role_path }}/files/app"
      args:
        nexus_server: "{{ nexus_host }}"
        version: maven-snapshots
    state: present
    source: build
    name: dhaeseq/projet-fil-rouge-groupe2:bibliotheque-app-preprod
    tag: latest
    push: yes
  when: inventory_hostname == "localhost"
  tags:
    - buildAndPushPreprodAppNexusImage

# REMOVE PREPROD LOCAL IMAGE
- name: Remove preprod app local image
  docker_image:
    state: absent
    name:  dhaeseq/projet-fil-rouge-groupe2
    tag: bibliotheque-app-preprod
  when: inventory_hostname == "localhost"
  tags:
    - buildAndPushPreprodAppNexusImage
    - removePreprodLocalAppImage

# BUILD PROD APP IMAGE FROM NEXUS AND PUSH DOCKERHUB
- name: Build prod app image from nexus and send it to DockerHub
  docker_image:
    build:
      path: "{{ role_path }}/files/app"
      args:
        nexus_server: "{{ nexus_host }}"
        version: maven-releases
    state: present
    source: build
    name: dhaeseq/projet-fil-rouge-groupe2:bibliotheque-app-prod
    tag: latest
    push: yes
  when: inventory_hostname == "localhost"
  tags:
    - buildAndPushProdAppNexusImage

# REMOVE PROD LOCAL IMAGE
- name: Remove prod app local image
  docker_image:
    state: absent
    name:  dhaeseq/projet-fil-rouge-groupe2
    tag: bibliotheque-app-prod
  when: inventory_hostname == "localhost"
  tags:
    - buildAndPushProdAppNexusImage
    - removeProdLocalAppImage

# REMOVE EXISTING BIBLIOTHEQUE APP
- name: Remove existing bibliotheque app
  docker_compose:
    project_src: /home/{{ ansible_ssh_user }}/bibliotheque/
    state: absent
    remove_images: all
  when: inventory_hostname != "localhost"
  tags:
    - removeOldBibliothequeApp

# COPY DOCKER-COMPOSE
- name: Copy docker-compose
  template:
    src: docker-compose.yml
    dest: /home/{{ ansible_ssh_user }}/bibliotheque/
  when: inventory_hostname != "localhost"
  tags:
    - copyBibliothequeAppDockerCompose

# PULL PROD APP IMAGE
- name: Pull prod app image
  docker_image:
    name: dhaeseq/projet-fil-rouge-groupe2:bibliotheque-app-prod
    source: pull
  when: inventory_hostname == "prodfilrouge"
  tags:
    - pullProdAppImage

# PULL PREPROD APP IMAGE
- name: Pull preprod app image
  docker_image:
    name: dhaeseq/projet-fil-rouge-groupe2:bibliotheque-app-preprod
    source: pull
  when: inventory_hostname == "devfilrouge"
  tags:
    - pullPreprodAppImage

# RUN IMAGE
- name: Run bibliotheque image
  docker_compose:
    project_src: /home/{{ ansible_ssh_user }}/bibliotheque
  when: inventory_hostname != "localhost"
  tags:
    - runBibliothequeAppImage
